<?php

/**
 * @file
 * Functions to support theming in the Demo Bartik theme.
 */

/*
 * Implements hook_preprocess_field__node__field_image__page.
 */
function demo_bartik_preprocess_field__node__field_image__page(&$variables) {
  $variables['itemsCount'] = sizeof($variables['items']);
}

/**
 * Implements hook_theme_suggestions_block_alter() for form templates.
 */
function demo_bartik_theme_suggestions_block_alter(array &$suggestions, array $variables) {
  $isBrandingBlock = $variables['elements']['#plugin_id'] == 'system_branding_block';

  if ($isBrandingBlock) {
    $suggestions[] = 'block__system_branding_block_custom';
  }
}
